spring:
  datasource:
    password: 52868816
    url: jdbc:mysql://localhost:3306/obj2_tp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
